### ISSUE TITLE
SUL-Solr Update / Searchwork Migration: Ensure existing incremental indexing processes point to new collection & are running

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sul-solr-configs#150]
- [x] At this point, the new “production” systems will be writing / using sw-solr-g. However, we will keep sw-solr-m running and with data writing to it as a backup option.
- [x] Required a cron be added sw-solr-g for getting data from bodoni.

Requires #148
Requires #149

**Comment by cbeer** [comment]
Fixed by https://github.com/sul-dlss/puppet/pull/3387.
