### ISSUE TITLE
SUL-Solr Update / Searchwork Migration: Point production Searchworks application at the new index collection in sul-solr (6.6.1)

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sul-solr-configs#151]
- [x] Bot boxes first (config update)
- [x] 3ish hours pause for internal review
- [x] Regular users second (all at same time) (config update)
- [x] Make sure it doesn’t burn down
- [x] “Release” announcement

Requires #150

**Comment by cbeer** [comment]
https://github.com/sul-dlss/shared_configs/pull/700
