### ISSUE TITLE
SUL-Solr Update / Searchwork Migration: Post-migration clean-up

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sul-solr-configs#154]
Clean-up work
- [x] Create sul-solr collections for sandboxes indexes.
       - https://github.com/sul-dlss/sul-solr-configs/pull/169
- [x] Get Searchworks Index standard data into those collections
- [x] Reindex any other data needed for those sandbox instances that is outside of what exists
  - I.e. Morison. Needs a solr config change to manage writing to new sul-solr collection as well.
- [x] Update sandbox instances to point at sul-solr, fix stuff in puppet
- [x] Assess & remove (or mark for removal) for solr collections no longer needed

**Comment by shelleydoljack** [comment]
Documenting this here so it's not lost. Per conversation with Chris, we decided to have the following collections in sul-solr:
- searchworks-morison-dev
- searchworks-bodoni-dev (the index for gryphon-search to use, which is currently called searchworks-gryphon-search-preview
- searchworks-morison-prod (currently called searchworks-morison)
- searchworks-prod
The idea is that `searchworks-indexing-stage` server would index to the `*-dev` collections and `searchworks-indexing-prod` would index to the `*-prod` collections.
